import axios from 'axios'

export const SEED_PASSWORD = 'SEED_PASSWORD'
export const ADD_PASSWORD = 'ADD_PASSWORD'
export const REMOVE_PASSWORD = 'REMOVE_PASSWORD'
export const  UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const SEARCH_PASSWORD = 'SEARCH_PASSWORD'
export const SET_URL = 'SET_URL'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_ID = 'SET_ID'
export const RESET = ' RESET'
export const SET_INDEX = 'SET_INDEX'
export const SET_CREATED = 'SET_CREATED'
